language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update
  - composer install --no-interaction
  - mkdir server
  - wget https://cdn.getbukkit.org/spigot/spigot-1.12.2.jar -P server/
  - printf "eula=true" > server/eula.txt
  - mkdir server/plugins
  - wget http://addons-origin.cursecdn.com/files/886/407/votifier-1.9.jar -P server/plugins/
  - java -Xms512M -Xmx1024M -jar server/spigot-1.12.2.jar &

script:
  - composer run test

after_script:
  - |
    if [ -f "build/logs/clover.xml" ]; then
      composer run upload-coveralls
      composer run upload-scrutinizer
    fi

notifications:
  email: false
